{
    "name": "PEC Manager (in Helpdesk)",
    "version": "1.5.2",
    "category": "Services/Helpdesk",
    "summary": "Manage PEC messages in Helpdesk App",
    "website": "https://github.com/madgrog/pec_manager",
    # optional dependency: "mail_debrand" from OCA/social
    "depends": ["mail", "helpdesk", "base_automation", "contacts", "hr"],
    "data": [
        'security/pec_manager_security.xml',
        'security/ir.model.access.csv',
        "data/base_automation_data.xml",
        "data/mail_template_data.xml",
        "data/mail_message_subtype_data.xml",
        "views/fetchmail_views.xml",
        "views/helpdesk_menu_icon_updated.xml",
        "views/helpdesk_ticket_views.xml",
        "views/mail_alias_domain_views.xml",
        "views/res_partner_views.xml",
    ],
    "application": True,
    "license": "AGPL-3",
    "author": "Luigi Lamorte",
    "uninstall_hook": "_restore_helpdesk",
}
